version: "3.7"
services:
  app:
    build:
      context: "."
    image: polyneme/qapages
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - uvicorn
      - qapages.entrypoints.fastapi_app:app
      - --reload
      - --host=0.0.0.0
      - --port=8000
    env_file:
      - .env
    ports:
      - "8000:8000"
  mongo:
    image: mongo:4.4-bionic
    volumes:
      - qapages_mongo_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "57017:27017"


volumes:
  qapages_mongo_data:
    driver: local